// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/stream.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InteractionEvent is a single danmu/comment event from a video session.
type InteractionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`              // video session identifier
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // video playback position in milliseconds (not wall clock)
	RawText       string                 `protobuf:"bytes,3,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`              // danmu / comment content
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // optional sender identifier
	RepeatCount   int32                  `protobuf:"varint,5,opt,name=repeat_count,json=repeatCount,proto3" json:"repeat_count,omitempty"` // number of merged identical events (set by batcher; 0 means 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionEvent) Reset() {
	*x = InteractionEvent{}
	mi := &file_api_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionEvent) ProtoMessage() {}

func (x *InteractionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionEvent.ProtoReflect.Descriptor instead.
func (*InteractionEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *InteractionEvent) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *InteractionEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *InteractionEvent) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *InteractionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InteractionEvent) GetRepeatCount() int32 {
	if x != nil {
		return x.RepeatCount
	}
	return 0
}

// PushAck is returned after a client streaming session completes.
type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_api_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_api_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PushAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WindowResult is the LLM-processed output for one aggregation window.
type WindowResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	WindowStart   int64                  `protobuf:"varint,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"` // inclusive, video timestamp ms
	WindowEnd     int64                  `protobuf:"varint,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`       // inclusive, video timestamp ms
	EmotionTag    string                 `protobuf:"bytes,4,opt,name=emotion_tag,json=emotionTag,proto3" json:"emotion_tag,omitempty"`     // e.g. "excited", "confused", "amused"
	CoreTopic     string                 `protobuf:"bytes,5,opt,name=core_topic,json=coreTopic,proto3" json:"core_topic,omitempty"`        // one-line summary of what viewers reacted to
	EventCount    int32                  `protobuf:"varint,6,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`    // number of events in this window
	ProcessedAt   int64                  `protobuf:"varint,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"` // wall-clock unix ms when result was produced (for latency display)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowResult) Reset() {
	*x = WindowResult{}
	mi := &file_api_proto_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowResult) ProtoMessage() {}

func (x *WindowResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowResult.ProtoReflect.Descriptor instead.
func (*WindowResult) Descriptor() ([]byte, []int) {
	return file_api_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *WindowResult) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WindowResult) GetWindowStart() int64 {
	if x != nil {
		return x.WindowStart
	}
	return 0
}

func (x *WindowResult) GetWindowEnd() int64 {
	if x != nil {
		return x.WindowEnd
	}
	return 0
}

func (x *WindowResult) GetEmotionTag() string {
	if x != nil {
		return x.EmotionTag
	}
	return ""
}

func (x *WindowResult) GetCoreTopic() string {
	if x != nil {
		return x.CoreTopic
	}
	return ""
}

func (x *WindowResult) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *WindowResult) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

var File_api_proto_stream_proto protoreflect.FileDescriptor

const file_api_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/stream.proto\x12\x06stream\"\xa7\x01\n" +
	"\x10InteractionEvent\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x19\n" +
	"\braw_text\x18\x03 \x01(\tR\arawText\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12!\n" +
	"\frepeat_count\x18\x05 \x01(\x05R\vrepeatCount\"9\n" +
	"\aPushAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xef\x01\n" +
	"\fWindowResult\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12!\n" +
	"\fwindow_start\x18\x02 \x01(\x03R\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x03 \x01(\x03R\twindowEnd\x12\x1f\n" +
	"\vemotion_tag\x18\x04 \x01(\tR\n" +
	"emotionTag\x12\x1d\n" +
	"\n" +
	"core_topic\x18\x05 \x01(\tR\tcoreTopic\x12\x1f\n" +
	"\vevent_count\x18\x06 \x01(\x05R\n" +
	"eventCount\x12!\n" +
	"\fprocessed_at\x18\a \x01(\x03R\vprocessedAt2J\n" +
	"\rStreamService\x129\n" +
	"\n" +
	"PushEvents\x12\x18.stream.InteractionEvent\x1a\x0f.stream.PushAck(\x01B8Z6github.com/AkikoAkaki/async-task-platform/api/proto;pbb\x06proto3"

var (
	file_api_proto_stream_proto_rawDescOnce sync.Once
	file_api_proto_stream_proto_rawDescData []byte
)

func file_api_proto_stream_proto_rawDescGZIP() []byte {
	file_api_proto_stream_proto_rawDescOnce.Do(func() {
		file_api_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stream_proto_rawDesc), len(file_api_proto_stream_proto_rawDesc)))
	})
	return file_api_proto_stream_proto_rawDescData
}

var file_api_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_stream_proto_goTypes = []any{
	(*InteractionEvent)(nil), // 0: stream.InteractionEvent
	(*PushAck)(nil),          // 1: stream.PushAck
	(*WindowResult)(nil),     // 2: stream.WindowResult
}
var file_api_proto_stream_proto_depIdxs = []int32{
	0, // 0: stream.StreamService.PushEvents:input_type -> stream.InteractionEvent
	1, // 1: stream.StreamService.PushEvents:output_type -> stream.PushAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_stream_proto_init() }
func file_api_proto_stream_proto_init() {
	if File_api_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stream_proto_rawDesc), len(file_api_proto_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stream_proto_goTypes,
		DependencyIndexes: file_api_proto_stream_proto_depIdxs,
		MessageInfos:      file_api_proto_stream_proto_msgTypes,
	}.Build()
	File_api_proto_stream_proto = out.File
	file_api_proto_stream_proto_goTypes = nil
	file_api_proto_stream_proto_depIdxs = nil
}
